// <auto-generated />
using System;
using LinkedOut.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkedOut.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511121946_AddProfilesAndUserSkills")]
    partial class AddProfilesAndUserSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkedOut.Api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Location = "Ukraine",
                            Name = "Tech Corp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Location = "Ukraine",
                            Name = "SoftServe"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Location = "Ukraine",
                            Name = "GlobalLogic"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Location = "Ukraine",
                            Name = "EPAM"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Location = "Ukraine",
                            Name = "Infopulse"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Location = "Ukraine",
                            Name = "Luxoft"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Location = "Ukraine",
                            Name = "Ciklum"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Location = "Ukraine",
                            Name = "Genesis"
                        });
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.ProfileSkill", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("ProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("profile_skills", (string)null);
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("requirements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000001"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000001"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000002"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000002"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000003"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000003"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000007"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000004"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000008"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000004"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000009"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000005"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000010"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000005"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000011"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000006"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000012"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000006"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000013"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000007"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000014"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000007"),
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000015"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000008"),
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000016"),
                            CompanyId = new Guid("11111111-1111-1111-1111-000000000008"),
                            Title = "Backend Engineer"
                        });
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.RequirementSkill", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("RequirementId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("requirement_skills", (string)null);
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Category = "Backend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = ".NET"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Category = "Backend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Category = "Backend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Category = "Backend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Category = "Frontend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Category = "Frontend",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Git"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Azure"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AWS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CI/CD"
                        });
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.ProfileSkill", b =>
                {
                    b.HasOne("LinkedOut.Api.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkedOut.Api.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.Requirement", b =>
                {
                    b.HasOne("LinkedOut.Api.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LinkedOut.Api.Entities.RequirementSkill", b =>
                {
                    b.HasOne("LinkedOut.Api.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkedOut.Api.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
